### ISSUE TITLE
Seartch with IMDB ID dosnt work

### ISSUE THREAD

**Issue by AdamRussak** [StalkR/imdb#10]
![image](https://user-images.githubusercontent.com/31593022/203439022-185e411e-f1bc-49af-bb64-8e0de3a7f33a.png)

i am searching using imdb id, and this is what i get (tryd from 2 computers amd & Arm) on version 1.0.11
full code snipet:
```go
package main

import (
	"flag"
	"fmt"
	"net/http"
	"os"

	"github.com/StalkR/imdb"
)

func main() {
	flag.Parse()
	if flag.NArg() == 0 {
		fmt.Fprintf(os.Stderr, "Usage: %s <search title>\n", os.Args[0])
		os.Exit(1)
	}

	client := http.DefaultClient
	fmt.Println(flag.Arg(0))
	t, err := imdb.NewTitle(client, flag.Arg(0))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(2)
	}

	fmt.Println(t.String())
}

```

**Comment by Chuchodavids** [comment]
Did you find a solution for this? I think this is a new error.

**Comment by AdamRussak** [comment]
i think its a language issue but I didn't have the time to look into it.
it should be set to "always en-US"

**Comment by StalkR** [comment]
I noticed it as well, the problem is that imdb recently deployed awswaf, so your requests are being denied.

See my latest commit 1350f14a7ee2f6015017e633606f216997b30f30 for a solution: just configure your http client (`http.DefaultClient`) to send a regular browser user agent instead of the default one (`Go-http-client/1.1`), and provided you don't trigger awswaf in another way (remain respectful, no rapid queries, spam, etc) then your requests shouldn't be immediately denied. I'll update the example.

It's not a language issue, but you can set it to get consistent results otherwise they get localized to the geo location guessed from the IP.

**Comment by AdamRussak** [comment]
> I noticed it as well, the problem is that imdb recently deployed awswaf, so your requests are being denied.
> 
> See my latest commit [1350f14](https://github.com/StalkR/imdb/commit/1350f14a7ee2f6015017e633606f216997b30f30) for a solution: just configure your http client (`http.DefaultClient`) to send a regular browser user agent instead of the default one (`Go-http-client/1.1`), and provided you don't trigger awswaf in another way (remain respectful, no rapid queries, spam, etc) then your requests shouldn't be immediately denied. I'll update the example.
> 
> It's not a language issue, but you can set it to get consistent results otherwise they get localized to the geo location guessed from the IP.

how do I set the language with HTTP.DefaultClient? in order to set language I need to be able to use the costume header.

**Comment by AdamRussak** [comment]
updated example works perfectly!!
thank you!
g8t job and keep it up :)
