### ISSUE TITLE
Get Release Info

### ISSUE THREAD

**Issue by shingsam** [StalkR/imdb#4]
How to get release Movie or Tv ? Like date month & year

Thnks,

**Comment by StalkR** [comment]
With this library you can only get the year, not day/month.

For example for http://www.imdb.com/title/tt0133093/ you get name "Matrix" and year "1999" (https://movie-db-api.appspot.com/title/tt0133093).

Extracting day/month is feasible though I suppose problematic because I would expect the information to be less generally available than just the year. You can usually find more detailed release information on http://www.imdb.com/title/tt0133093/releaseinfo (and it's usually per country). The library already parses this page (in https://github.com/StalkR/imdb/blob/master/title.go#L319) to extract the AKAs ("also known as", alternate movie titles) but nothing more.

Series are the same, you can get the year but for more precise, what should it be? the day/month of the first pilot? I'm not sure where is this info, maybe on the main series page, or on the individual page of the first episode.
