### ISSUE TITLE
Can not get search results

### ISSUE THREAD

**Issue by razsteinmetz** [StalkR/imdb#9]
I think imdb changed their web search result page and removed the /table item.  So no results are returned.
It does that some of the times, I get no results about half of the times.

**Comment by StalkR** [comment]
Hey, I noticed it too in my weekly integration test last week, I added support on HEAD for the new search page in (9aa9826c40306500b5c2a6eadd834dcc94e55a5d) and also kept the old search (b80a305a5273156873de7f7baeb209dc76238fb4) because indeed, they seem to do a progressive launch so we can end with both.

I tagged head with v1.0.9 maybe that'll help you pick up the fixes, let me know otherwise!
